In [1]:
raw_data = {
    "User ID": [
        "101",
        "102",
        "103",
        "104",
        "105",
        "106",
        "107",
        "108",
        "109",
        "110",
        "111",
        "112",
        "113",
        "114",
        "115",
    ],
    "User Name": [
        "John Doe",
        "Scott Tiger",
        "Alice Smith",
        "Bob Johnson",
        "Emma Watson",
        "Charlie Brown",
        "David Miller",
        "Eva Green",
        "Frank Wright",
        "Grace Hopper",
        "Hank Voight",
        "Ivy Chen",
        "Jack Ryan",
        "Karen Page",
        "Leo Fitz",
    ],
    "Region": [
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
    ],
    "Category": [
        "Electronics",
        "Furniture",
        "Electronics",
        "Office Supplies",
        "Furniture",
        "Electronics",
        "Office Supplies",
        "Furniture",
        "Electronics",
        "Furniture",
        "Office Supplies",
        "Electronics",
        "Furniture",
        "Office Supplies",
        "Electronics",
    ],
    "Join Date": [
        "2024-05-01",
        "2024-06-12",
        "2024-01-15",
        "2024-02-20",
        "2024-03-05",
        "2024-04-10",
        "2024-05-18",
        "2024-06-25",
        "2024-07-02",
        "2024-08-14",
        "2024-09-09",
        "2024-10-30",
        "2024-11-11",
        "2024-12-01",
        "2024-12-15",
    ],
    "Sales Amount": [
        "$6,500.00",
        "$3,200.50",
        "$8,900.00",
        "$1,400.00",
        "$5,200.75",
        "$7,100.00",
        "$4,800.00",
        "$9,500.25",
        "$2,100.00",
        "$6,200.00",
        "$3,900.50",
        "$11,000.00",
        "$5,800.00",
        "$8,300.00",
        "$4,200.00",
    ],
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(raw_data)

In [4]:
df

   User ID      User Name Region         Category   Join Date Sales Amount
0      101       John Doe  North      Electronics  2024-05-01    $6,500.00
1      102    Scott Tiger  South        Furniture  2024-06-12    $3,200.50
2      103    Alice Smith   East      Electronics  2024-01-15    $8,900.00
3      104    Bob Johnson   West  Office Supplies  2024-02-20    $1,400.00
4      105    Emma Watson  North        Furniture  2024-03-05    $5,200.75
5      106  Charlie Brown  South      Electronics  2024-04-10    $7,100.00
6      107   David Miller   East  Office Supplies  2024-05-18    $4,800.00
7      108      Eva Green   West        Furniture  2024-06-25    $9,500.25
8      109   Frank Wright  North      Electronics  2024-07-02    $2,100.00
9      110   Grace Hopper  South        Furniture  2024-08-14    $6,200.00
10     111    Hank Voight   East  Office Supplies  2024-09-09    $3,900.50
11     112       Ivy Chen   West      Electronics  2024-10-30   $11,000.00
12     113      Jack Ryan  North        Furniture  2024-11-11    $5,800.00
13     114     Karen Page  South  Office Supplies  2024-12-01    $8,300.00
14     115       Leo Fitz   East      Electronics  2024-12-15    $4,200.00

In [5]:
# Rename columns
df = df.rename(columns={
    "User ID": "user_id",
    "User Name": "user_name",
    "Join Date": "join_date",
    "Region": "region",
    "Category": "category",
    "Sales Amount": "sales_amount"
})

In [6]:
df

   user_id      user_name region         category   join_date sales_amount
0      101       John Doe  North      Electronics  2024-05-01    $6,500.00
1      102    Scott Tiger  South        Furniture  2024-06-12    $3,200.50
2      103    Alice Smith   East      Electronics  2024-01-15    $8,900.00
3      104    Bob Johnson   West  Office Supplies  2024-02-20    $1,400.00
4      105    Emma Watson  North        Furniture  2024-03-05    $5,200.75
5      106  Charlie Brown  South      Electronics  2024-04-10    $7,100.00
6      107   David Miller   East  Office Supplies  2024-05-18    $4,800.00
7      108      Eva Green   West        Furniture  2024-06-25    $9,500.25
8      109   Frank Wright  North      Electronics  2024-07-02    $2,100.00
9      110   Grace Hopper  South        Furniture  2024-08-14    $6,200.00
10     111    Hank Voight   East  Office Supplies  2024-09-09    $3,900.50
11     112       Ivy Chen   West      Electronics  2024-10-30   $11,000.00
12     113      Jack Ryan  North        Furniture  2024-11-11    $5,800.00
13     114     Karen Page  South  Office Supplies  2024-12-01    $8,300.00
14     115       Leo Fitz   East      Electronics  2024-12-15    $4,200.00

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       15 non-null     str
 1   user_name     15 non-null     str
 2   region        15 non-null     str
 3   category      15 non-null     str
 4   join_date     15 non-null     str
 5   sales_amount  15 non-null     str
dtypes: str(6)
memory usage: 852.0 bytes

In [9]:
# Convert data types of columns
df["user_id"] = df["user_id"].astype("int64")

df["join_date"] = pd.to_datetime(df["join_date"])

df["sales_amount"] = (
    df["sales_amount"].str.replace("$", "", regex=False).str.replace(",", "").astype(float)
)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       15 non-null     int64
 1   user_name     15 non-null     str
 2   region        15 non-null     str
 3   category      15 non-null     str
 4   join_date     15 non-null     datetime64[us]
 5   sales_amount  15 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 852.0 bytes

In [12]:
# Filter records where sales amount > 5000
filtered_sorted_df = (
    df[df["sales_amount"] > 5000]
    .sort_values(by=["region", "sales_amount"], ascending=[True, False])
    .reset_index(drop=True)
)

In [13]:
filtered_sorted_df

   user_id      user_name region         category  join_date  sales_amount
0      103    Alice Smith   East      Electronics 2024-01-15       8900.00
1      101       John Doe  North      Electronics 2024-05-01       6500.00
2      113      Jack Ryan  North        Furniture 2024-11-11       5800.00
3      105    Emma Watson  North        Furniture 2024-03-05       5200.75
4      114     Karen Page  South  Office Supplies 2024-12-01       8300.00
5      106  Charlie Brown  South      Electronics 2024-04-10       7100.00
6      110   Grace Hopper  South        Furniture 2024-08-14       6200.00
7      112       Ivy Chen   West      Electronics 2024-10-30      11000.00
8      108      Eva Green   West        Furniture 2024-06-25       9500.25

In [14]:
# Group columns by region and category and calculate sum and mean of sales amount
grouped_summary_df = (
    df.groupby(["region", "category"])
    .agg(total_sales=("sales_amount", "sum"), avg_sales=("sales_amount", "mean"))
    .reset_index()
)

In [15]:
grouped_summary_df

  region         category  total_sales  avg_sales
0   East      Electronics     13100.00   6550.000
1   East  Office Supplies      8700.50   4350.250
2  North      Electronics      8600.00   4300.000
3  North        Furniture     11000.75   5500.375
4  South      Electronics      7100.00   7100.000
5  South        Furniture      9400.50   4700.250
6  South  Office Supplies      8300.00   8300.000
7   West      Electronics     11000.00  11000.000
8   West        Furniture      9500.25   9500.250
9   West  Office Supplies      1400.00   1400.000