In [14]:
import pandas as pd
import numpy as np

In [15]:
# Generate Data
data = {
    'Customer_ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    'Age': [25, 34, np.nan, 45, 29, np.nan, 52, 38, np.nan, 31],
    'Gender': ['Male', 'Female', 'Female', np.nan, 'Male', 'Female', np.nan, 'Male', 'Female', 'Male'],
    'Income_USD': [55000, 62000, 48000, 71000, np.nan, 53000, 89000, np.nan, 61000, 58000],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Chicago', np.nan, 'Miami', 'New York', 'Houston'],
    'Purchase_Amount': [120.5, 250.0, 85.0, np.nan, 310.0, np.nan, 450.0, 95.0, 210.0, 175.0]
}

In [16]:
# Convert the data into a pandas data frame
df = pd.DataFrame(data)

In [17]:
df

   Customer_ID   Age  Gender  Income_USD         City  Purchase_Amount
0         1001  25.0    Male     55000.0     New York            120.5
1         1002  34.0  Female     62000.0  Los Angeles            250.0
2         1003   NaN  Female     48000.0      Chicago             85.0
3         1004  45.0     NaN     71000.0      Houston              NaN
4         1005  29.0    Male         NaN      Phoenix            310.0
5         1006   NaN  Female     53000.0      Chicago              NaN
6         1007  52.0     NaN     89000.0          NaN            450.0
7         1008  38.0    Male         NaN        Miami             95.0
8         1009   NaN  Female     61000.0     New York            210.0
9         1010  31.0    Male     58000.0      Houston            175.0

In [18]:
# count missing or null values
df.isnull().sum()

Customer_ID        0
Age                3
Gender             2
Income_USD         2
City               1
Purchase_Amount    2
dtype: int64

In [19]:
# fill missing values

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Gender'] = df['Gender'].fillna('UnKnown')
df['Income_USD'] = df['Income_USD'].fillna(df['Income_USD'].mean())
df['Purchase_Amount'] = df['Purchase_Amount'].fillna(0)

In [20]:
df

   Customer_ID        Age   Gender  Income_USD         City  Purchase_Amount
0         1001  25.000000     Male     55000.0     New York            120.5
1         1002  34.000000   Female     62000.0  Los Angeles            250.0
2         1003  36.285714   Female     48000.0      Chicago             85.0
3         1004  45.000000  UnKnown     71000.0      Houston              0.0
4         1005  29.000000     Male     62125.0      Phoenix            310.0
5         1006  36.285714   Female     53000.0      Chicago              0.0
6         1007  52.000000  UnKnown     89000.0          NaN            450.0
7         1008  38.000000     Male     62125.0        Miami             95.0
8         1009  36.285714   Female     61000.0     New York            210.0
9         1010  31.000000     Male     58000.0      Houston            175.0

In [24]:
# Drop the row where City is NaN
df = df.dropna(subset=['City'])

In [25]:
df

   Customer_ID        Age   Gender  Income_USD         City  Purchase_Amount
0         1001  25.000000     Male     55000.0     New York            120.5
1         1002  34.000000   Female     62000.0  Los Angeles            250.0
2         1003  36.285714   Female     48000.0      Chicago             85.0
3         1004  45.000000  UnKnown     71000.0      Houston              0.0
4         1005  29.000000     Male     62125.0      Phoenix            310.0
5         1006  36.285714   Female     53000.0      Chicago              0.0
7         1008  38.000000     Male     62125.0        Miami             95.0
8         1009  36.285714   Female     61000.0     New York            210.0
9         1010  31.000000     Male     58000.0      Houston            175.0

In [26]:
df.isnull().sum()

Customer_ID        0
Age                0
Gender             0
Income_USD         0
City               0
Purchase_Amount    0
dtype: int64

In [27]:
products = pd.read_csv('PRODUCT.csv')

In [28]:
# Display Product Category values
products.value_counts(subset=['Category'])

Category
Home Appliances    34
Kitchen            28
Electronics        26
Wearables          21
Furniture          16
Audio              15
Computers          10
Name: count, dtype: int64

In [29]:
products.nunique()

Record_ID              150
Month                   15
Product_Name            10
Category                 7
Original_Price_USD     148
Discount_Percent         6
Effective_Price_USD    150
Ad_Expenditure_USD     150
Customer_Visits        150
Units_Sold             145
Total_Sales_USD        150
Gross_Profit_USD       150
Net_Profit_USD         150
dtype: int64